### ISSUE TITLE
error after updating to version 2.3.1

### ISSUE THREAD

**Issue by erredeco** [comsolit/owl_slider#11]
After updating to version 2.3.1 I have on FE an error like:
```
Code: 201601111002371cfc0175
```
(the string may vary);
full error log:
```
Mon, 11 Jan 2016 10:27:04 +0100 [ALERT] request="b7effb3b4dc76" component="TYPO3.CMS.Frontend.ContentObject.Exception.ProductionExceptionHandler": Oops, an error occurred! Code: 20160111102703573e472b - {"exception":"exception 'TYPO3\\CMS\\Core\\Error\\Exception' with message 'PHP Warning: array_replace(): Argument #2 is not an array in C:\\xampp\\htdocs\\typo3.test7.it\\typo3conf\\ext\\owl_slider\\Classes\\Controller\\ItemController.php line 103' in C:\\typo3-src\\typo3_src-7.6.2\\typo3\\sysext\\core\\Classes\\Error\\ErrorHandler.php:111\nStack trace:\n#0 [internal function]: TYPO3\\CMS\\Core\\Error\\ErrorHandler->handleError(2, 'array_replace()...', 'C:\\\\xampp\\\\htdocs...', 103, Array)\n#1 C:\\xampp\\htdocs\\typo3.test7.it\\typo3conf\\ext\\owl_slider\\Classes\\Controller\\ItemController.php(103): array_replace(Array, NULL)\n#2 C:\\xampp\\htdocs\\typo3.test7.it\\typo3conf\\ext\\owl_slider\\Classes\\Controller\\ItemController.php(56): TYPO3\\OwlSlider\\Controller\\ItemController->applyCustomConfig(Array, NULL)\n#3 [internal function]: TYPO3\\OwlSlider\\Controller\\ItemController->listAction()\n#4 C:\\typo3-src\\typo3_src-7.6.2\\typo3\\sysext\\extbase\\Classes\\Mvc\\Controller\\ActionController.php(283): call_user_func_array(Array, Array)\n#5 C:\\typo3-src\\typo3_src-7.6.2\\typo3\\sysext\\extbase\\Classes\\Mvc\\Controller\\ActionController.php(176): TYPO3\\CMS\\Extbase\\Mvc\\Controller\\ActionController->callActionMethod()\n#6 C:\\typo3-src\\typo3_src-7.6.2\\typo3\\sysext\\extbase\\Classes\\Mvc\\Dispatcher.php(86): TYPO3\\CMS\\Extbase\\Mvc\\Controller\\ActionController->processRequest(Object(TYPO3\\CMS\\Extbase\\Mvc\\Web\\Request), Object(TYPO3\\CMS\\Extbase\\Mvc\\Web\\Response))\n#7 C:\\typo3-src\\typo3_src-7.6.2\\typo3\\sysext\\extbase\\Classes\\Mvc\\Web\\FrontendRequestHandler.php(69): TYPO3\\CMS\\Extbase\\Mvc\\Dispatcher->dispatch(Object(TYPO3\\CMS\\Extbase\\Mvc\\Web\\Request), Object(TYPO3\\CMS\\Extbase\\Mvc\\Web\\Response))\n#8 C:\\typo3-src\\typo3_src-7.6.2\\typo3\\sysext\\extbase\\Classes\\Core\\Bootstrap.php(206): TYPO3\\CMS\\Extbase\\Mvc\\Web\\FrontendRequestHandler->handleRequest()\n#9 C:\\typo3-src\\typo3_src-7.6.2\\typo3\\sysext\\extbase\\Classes\\Core\\Bootstrap.php(193): TYPO3\\CMS\\Extbase\\Core\\Bootstrap->handleRequest()\n#10 [internal function]: TYPO3\\CMS\\Extbase\\Core\\Bootstrap->run('', Array)\n#11 C:\\typo3-src\\typo3_src-7.6.2\\typo3\\sysext\\frontend\\Classes\\ContentObject\\ContentObjectRenderer.php(7315): call_user_func_array(Array, Array)\n#12 C:\\typo3-src\\typo3_src-7.6.2\\typo3\\sysext\\frontend\\Classes\\ContentObject\\UserContentObject.php(40): TYPO3\\CMS\\Frontend\\ContentObject\\ContentObjectRenderer->callUserFunction('TYPO3\\\\CMS\\\\Extba...', Array, '')\n#13 C:\\typo3-src\\typo3_src-7.6.2\\typo3\\sysext\\frontend\\Classes\\ContentObject\\ContentObjectRenderer.php(943): TYPO3\\CMS\\Frontend\\ContentObject\\UserContentObject->render(Array)\n#14 C:\\typo3-src\\typo3_src-7.6.2\\typo3\\sysext\\frontend\\Classes\\ContentObject\\ContentObjectRenderer.php(859): TYPO3\\CMS\\Frontend\\ContentObject\\ContentObjectRenderer->render(Object(TYPO3\\CMS\\Frontend\\ContentObject\\UserContentObject), Array)\n#15 C:\\typo3-src\\typo3_src-7.6.2\\typo3\\sysext\\fluid\\Classes\\ViewHelpers\\CObjectViewHelper.php(119): TYPO3\\CMS\\Frontend\\ContentObject\\ContentObjectRenderer->cObjGetSingle('USER', Array)\n#16 [internal function]: TYPO3\\CMS\\Fluid\\ViewHelpers\\CObjectViewHelper->render('tt_content.list...', Array, NULL, '')\n#17 C:\\typo3-src\\typo3_src-7.6.2\\typo3\\sysext\\fluid\\Classes\\Core\\ViewHelper\\AbstractViewHelper.php(261): call_user_func_array(Array, Array)\n#18 C:\\typo3-src\\typo3_src-7.6.2\\typo3\\sysext\\fluid\\Classes\\Core\\ViewHelper\\AbstractViewHelper.php(242): TYPO3\\CMS\\Fluid\\Core\\ViewHelper\\AbstractViewHelper->callRenderMethod()\n#19 C:\\xampp\\htdocs\\typo3.test7.it\\typo3temp\\Cache\\Code\\fluid_template\\Standalone_template_file_List_932522d35a23d286e230dfd1061a9347d02811e2.php(46): TYPO3\\CMS\\Fluid\\Core\\ViewHelper\\AbstractViewHelper->initializeArgumentsAndRender()\n#20 C:\\typo3-src\\typo3_src-7.6.2\\typo3\\sysext\\fluid\\Classes\\View\\AbstractTemplateView.php(230): FluidCache_Standalone_template_file_List_932522d35a23d286e230dfd1061a9347d02811e2->section_040f06fd774092478d450774f5ba30c5da78acc8(Object(TYPO3\\CMS\\Fluid\\Core\\Rendering\\RenderingContext))\n#21 C:\\typo3-src\\typo3_src-7.6.2\\typo3\\sysext\\fluid\\Classes\\ViewHelpers\\RenderViewHelper.php(121): TYPO3\\CMS\\Fluid\\View\\AbstractTemplateView->renderSection('content', Array, false)\n#22 C:\\xampp\\htdocs\\typo3.test7.it\\typo3temp\\Cache\\Code\\fluid_template\\Standalone_layout_HeaderContentFooter_926a0e24d76157960987fc844e0d427da30a23dd.php(62): TYPO3\\CMS\\Fluid\\ViewHelpers\\RenderViewHelper::renderStatic(Array, Object(Closure), Object(TYPO3\\CMS\\Fluid\\Core\\Rendering\\RenderingContext))\n#23 C:\\typo3-src\\typo3_src-7.6.2\\typo3\\sysext\\fluid\\Classes\\View\\AbstractTemplateView.php(189): FluidCache_Standalone_layout_HeaderContentFooter_926a0e24d76157960987fc844e0d427da30a23dd->render(Object(TYPO3\\CMS\\Fluid\\Core\\Rendering\\RenderingContext))\n#24 C:\\typo3-src\\typo3_src-7.6.2\\typo3\\sysext\\frontend\\Classes\\ContentObject\\FluidTemplateContentObject.php(300): TYPO3\\CMS\\Fluid\\View\\AbstractTemplateView->render()\n#25 C:\\typo3-src\\typo3_src-7.6.2\\typo3\\sysext\\frontend\\Classes\\ContentObject\\FluidTemplateContentObject.php(102): TYPO3\\CMS\\Frontend\\ContentObject\\FluidTemplateContentObject->renderFluidView()\n#26 C:\\typo3-src\\typo3_src-7.6.2\\typo3\\sysext\\frontend\\Classes\\ContentObject\\ContentObjectRenderer.php(943): TYPO3\\CMS\\Frontend\\ContentObject\\FluidTemplateContentObject->render(Array)\n#27 C:\\typo3-src\\typo3_src-7.6.2\\typo3\\sysext\\frontend\\Classes\\ContentObject\\ContentObjectRenderer.php(859): TYPO3\\CMS\\Frontend\\ContentObject\\ContentObjectRenderer->render(Object(TYPO3\\CMS\\Frontend\\ContentObject\\FluidTemplateContentObject), Array)\n#28 C:\\typo3-src\\typo3_src-7.6.2\\typo3\\sysext\\frontend\\Classes\\ContentObject\\ContentObjectRenderer.php(841): TYPO3\\CMS\\Frontend\\ContentObject\\ContentObjectRenderer->cObjGetSingle('FLUIDTEMPLATE', Array, 'lib.fluidConten...')\n#29 C:\\typo3-src\\typo3_src-7.6.2\\typo3\\sysext\\frontend\\Classes\\ContentObject\\CaseContentObject.php(44): TYPO3\\CMS\\Frontend\\ContentObject\\ContentObjectRenderer->cObjGetSingle('< lib.fluidCont...', Array, 'list')\n#30 C:\\typo3-src\\typo3_src-7.6.2\\typo3\\sysext\\frontend\\Classes\\ContentObject\\ContentObjectRenderer.php(943): TYPO3\\CMS\\Frontend\\ContentObject\\CaseContentObject->render(Array)\n#31 C:\\typo3-src\\typo3_src-7.6.2\\typo3\\sysext\\frontend\\Classes\\ContentObject\\ContentObjectRenderer.php(859): TYPO3\\CMS\\Frontend\\ContentObject\\ContentObjectRenderer->render(Object(TYPO3\\CMS\\Frontend\\ContentObject\\CaseContentObject), Array)\n#32 C:\\typo3-src\\typo3_src-7.6.2\\typo3\\sysext\\frontend\\Classes\\ContentObject\\ContentObjectRenderer.php(841): TYPO3\\CMS\\Frontend\\ContentObject\\ContentObjectRenderer->cObjGetSingle('CASE', Array, 'tt_content')\n#33 C:\\typo3-src\\typo3_src-7.6.2\\typo3\\sysext\\frontend\\Classes\\ContentObject\\RecordsContentObject.php(119): TYPO3\\CMS\\Frontend\\ContentObject\\ContentObjectRenderer->cObjGetSingle('<tt_content', NULL, '')\n#34 C:\\typo3-src\\typo3_src-7.6.2\\typo3\\sysext\\frontend\\Classes\\ContentObject\\ContentObjectRenderer.php(943): TYPO3\\CMS\\Frontend\\ContentObject\\RecordsContentObject->render(Array)\n#35 C:\\typo3-src\\typo3_src-7.6.2\\typo3\\sysext\\frontend\\Classes\\ContentObject\\ContentObjectRenderer.php(859): TYPO3\\CMS\\Frontend\\ContentObject\\ContentObjectRenderer->render(Object(TYPO3\\CMS\\Frontend\\ContentObject\\RecordsContentObject), Array)\n#36 C:\\xampp\\htdocs\\typo3.test7.it\\typo3conf\\ext\\vhs\\Classes\\ViewHelpers\\Content\\AbstractContentViewHelper.php(190): TYPO3\\CMS\\Frontend\\ContentObject\\ContentObjectRenderer->cObjGetSingle('RECORDS', Array)\n#37 C:\\xampp\\htdocs\\typo3.test7.it\\typo3conf\\ext\\vhs\\Classes\\ViewHelpers\\Content\\AbstractContentViewHelper.php(158): FluidTYPO3\\Vhs\\ViewHelpers\\Content\\AbstractContentViewHelper->renderRecord(Array)\n#38 C:\\xampp\\htdocs\\typo3.test7.it\\typo3conf\\ext\\vhs\\Classes\\ViewHelpers\\Content\\AbstractContentViewHelper.php(79): FluidTYPO3\\Vhs\\ViewHelpers\\Content\\AbstractContentViewHelper->getRenderedRecords(Array)\n#39 C:\\xampp\\htdocs\\typo3.test7.it\\typo3conf\\ext\\vhs\\Classes\\ViewHelpers\\Content\\RenderViewHelper.php(45): FluidTYPO3\\Vhs\\ViewHelpers\\Content\\AbstractContentViewHelper->getContentRecords()\n#40 [internal function]: FluidTYPO3\\Vhs\\ViewHelpers\\Content\\RenderViewHelper->render()\n#41 C:\\typo3-src\\typo3_src-7.6.2\\typo3\\sysext\\fluid\\Classes\\Core\\ViewHelper\\AbstractViewHelper.php(261): call_user_func_array(Array, Array)\n#42 C:\\typo3-src\\typo3_src-7.6.2\\typo3\\sysext\\fluid\\Classes\\Core\\ViewHelper\\AbstractViewHelper.php(242): TYPO3\\CMS\\Fluid\\Core\\ViewHelper\\AbstractViewHelper->callRenderMethod()\n#43 C:\\xampp\\htdocs\\typo3.test7.it\\typo3temp\\Cache\\Code\\fluid_template\\Standalone_template_file_Home_c53740e72e10b8eb08a2008641476856165c3623.php(52): TYPO3\\CMS\\Fluid\\Core\\ViewHelper\\AbstractViewHelper->initializeArgumentsAndRender()\n#44 C:\\typo3-src\\typo3_src-7.6.2\\typo3\\sysext\\fluid\\Classes\\View\\AbstractTemplateView.php(230): FluidCache_Standalone_template_file_Home_c53740e72e10b8eb08a2008641476856165c3623->section_62bce9422ff2d14f69ab80a154510232fc8a9afd(Object(TYPO3\\CMS\\Fluid\\Core\\Rendering\\RenderingContext))\n#45 C:\\typo3-src\\typo3_src-7.6.2\\typo3\\sysext\\fluid\\Classes\\ViewHelpers\\RenderViewHelper.php(121): TYPO3\\CMS\\Fluid\\View\\AbstractTemplateView->renderSection('Main', Array, false)\n#46 C:\\xampp\\htdocs\\typo3.test7.it\\typo3temp\\Cache\\Code\\fluid_template\\Standalone_layout_Default_5230c5e63d88c5c998a8698f3b7d2a7a95ad932e.php(136): TYPO3\\CMS\\Fluid\\ViewHelpers\\RenderViewHelper::renderStatic(Array, Object(Closure), Object(TYPO3\\CMS\\Fluid\\Core\\Rendering\\RenderingContext))\n#47 C:\\typo3-src\\typo3_src-7.6.2\\typo3\\sysext\\fluid\\Classes\\View\\AbstractTemplateView.php(189): FluidCache_Standalone_layout_Default_5230c5e63d88c5c998a8698f3b7d2a7a95ad932e->render(Object(TYPO3\\CMS\\Fluid\\Core\\Rendering\\RenderingContext))\n#48 C:\\typo3-src\\typo3_src-7.6.2\\typo3\\sysext\\frontend\\Classes\\ContentObject\\FluidTemplateContentObject.php(300): TYPO3\\CMS\\Fluid\\View\\AbstractTemplateView->render()\n#49 C:\\typo3-src\\typo3_src-7.6.2\\typo3\\sysext\\frontend\\Classes\\ContentObject\\FluidTemplateContentObject.php(102): TYPO3\\CMS\\Frontend\\ContentObject\\FluidTemplateContentObject->renderFluidView()\n#50 C:\\typo3-src\\typo3_src-7.6.2\\typo3\\sysext\\frontend\\Classes\\ContentObject\\ContentObjectRenderer.php(943): TYPO3\\CMS\\Frontend\\ContentObject\\FluidTemplateContentObject->render(Array)\n#51 C:\\typo3-src\\typo3_src-7.6.2\\typo3\\sysext\\frontend\\Classes\\ContentObject\\ContentObjectRenderer.php(859): TYPO3\\CMS\\Frontend\\ContentObject\\ContentObjectRenderer->render(Object(TYPO3\\CMS\\Frontend\\ContentObject\\FluidTemplateContentObject), Array)\n#52 C:\\typo3-src\\typo3_src-7.6.2\\typo3\\sysext\\frontend\\Classes\\ContentObject\\ContentObjectRenderer.php(841): TYPO3\\CMS\\Frontend\\ContentObject\\ContentObjectRenderer->cObjGetSingle('FLUIDTEMPLATE', Array, 'lib.stdContent')\n#53 C:\\typo3-src\\typo3_src-7.6.2\\typo3\\sysext\\frontend\\Classes\\ContentObject\\ContentObjectRenderer.php(805): TYPO3\\CMS\\Frontend\\ContentObject\\ContentObjectRenderer->cObjGetSingle('< lib.stdConten...', NULL, '10')\n#54 C:\\typo3-src\\typo3_src-7.6.2\\typo3\\sysext\\frontend\\Classes\\Page\\PageGenerator.php(210): TYPO3\\CMS\\Frontend\\ContentObject\\ContentObjectRenderer->cObjGet(Array)\n#55 C:\\typo3-src\\typo3_src-7.6.2\\typo3\\sysext\\frontend\\Classes\\Http\\RequestHandler.php(216): TYPO3\\CMS\\Frontend\\Page\\PageGenerator::renderContent()\n#56 C:\\typo3-src\\typo3_src-7.6.2\\typo3\\sysext\\core\\Classes\\Core\\Bootstrap.php(302): TYPO3\\CMS\\Frontend\\Http\\RequestHandler->handleRequest(Object(TYPO3\\CMS\\Core\\Http\\ServerRequest))\n#57 C:\\typo3-src\\typo3_src-7.6.2\\typo3\\sysext\\frontend\\Classes\\Http\\Application.php(78): TYPO3\\CMS\\Core\\Core\\Bootstrap->handleRequest(Object(TYPO3\\CMS\\Core\\Http\\ServerRequest))\n#58 C:\\typo3-src\\typo3_src-7.6.2\\index.php(33): TYPO3\\CMS\\Frontend\\Http\\Application->run()\n#59 [internal function]: {closure}()\n#60 C:\\typo3-src\\typo3_src-7.6.2\\index.php(34): call_user_func(Object(Closure))\n#61 {main}"}
```

**Comment by larz** [comment]
Oh, I'm sorry forgot the annotation!

**Comment by erredeco** [comment]
I've downloaded from TER the version 2.3.2 and deleted cache from install tool, but it still doesn't work... is there something else I should do?

**Comment by larz** [comment]
did you delete also the content in typo3temp/ folder?

**Comment by erredeco** [comment]
I've just done that, too; but the error remains the same

**Comment by larz** [comment]
I'm wondering is this Problem still existing.

**Comment by erredeco** [comment]
I still have the same problem :(
